#!/usr/bin/env node

import { Command } from "commander";
import { execSync } from "node:child_process";
import {
  mkdirSync,
  writeFileSync,
  copyFileSync,
  chmodSync,
  existsSync,
  renameSync,
  rmSync,
  readFileSync,
  readdirSync,
  realpathSync,
} from "node:fs";
import { join, dirname, resolve } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import { loadConfig } from "./config.js";
import { query } from "./spawner.js";
import type { SubMcpConfig } from "./types.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SUB_MCP_DIR = join(homedir(), ".sub-mcp");
const BIN_DIR = join(SUB_MCP_DIR, "bin");

/** Write to a temp file then rename — atomic on POSIX, safe for concurrent reads. */
function atomicWrite(path: string, content: string, mode = 0o644): void {
  const tmp = `${path}.tmp.${process.pid}`;
  try {
    writeFileSync(tmp, content, { mode });
    renameSync(tmp, path);
  } finally {
    try { rmSync(tmp, { force: true }); } catch { /* best-effort cleanup */ }
  }
}

/** Build the cache object that gets written to ~/.sub-mcp/mcp-config.json. */
function buildCache(config: SubMcpConfig): object {
  return {
    mcpServers: config.mcpServers,
    profiles: Object.fromEntries(
      Object.entries(config.profiles).map(([name, p]) => [
        name,
        { servers: p.servers, isolateMcp: p.isolateMcp, systemPrompt: p.systemPrompt },
      ])
    ),
    defaults: config.defaults,
  };
}

/** Find the config source file path (for copying to ~/.sub-mcp/). */
function findConfigSourcePath(explicitPath?: string): string | undefined {
  if (explicitPath) return resolve(explicitPath);
  for (const p of ["profiles.yml", "profiles.yaml", "sub-mcp.yml", "sub-mcp.yaml"]) {
    const candidate = resolve(p);
    if (existsSync(candidate)) return candidate;
  }
  return undefined;
}

const GENERATED_MARKER = "<!-- Generated by sub-mcp. Do not edit manually. -->";

/**
 * Generate .claude/agents/<profile>.md files with mcpServers frontmatter.
 * This is Claude Code's native mechanism for giving subagents MCP access
 * in interactive sessions (where the CLI wrapper is not invoked).
 */
export function generateAgentFiles(config: SubMcpConfig, projectDir: string): string[] {
  const agentsDir = join(projectDir, ".claude", "agents");
  mkdirSync(agentsDir, { recursive: true });

  const generated: string[] = [];

  for (const [profileName, profile] of Object.entries(config.profiles)) {
    const filePath = join(agentsDir, `${profileName}.md`);

    // Build frontmatter object — uses Claude Code's native agent format:
    // name (required), description (required), mcpServers (list of inline defs
    // or string refs), model, tools, etc.
    const frontmatter: Record<string, unknown> = {
      name: profileName,
      description: profile.description,
    };

    // mcpServers is a list — each entry is an inline definition scoped to this
    // subagent only (server connects when subagent starts, disconnects when done).
    // This keeps MCP tool schemas OUT of the main session's context.
    if (profile.servers.length > 0) {
      const mcpServers: Array<Record<string, unknown>> = [];
      for (const serverName of profile.servers) {
        const server = config.mcpServers[serverName];
        const entry: Record<string, unknown> = {
          [serverName]: {
            type: "stdio",
            command: server.command,
            args: server.args,
            ...(server.env ? { env: server.env } : {}),
          },
        };
        mcpServers.push(entry);
      }
      frontmatter.mcpServers = mcpServers;
    }

    // Add model if specified
    if (profile.model) {
      frontmatter.model = profile.model;
    }

    // Serialize frontmatter
    const yamlStr = yaml.dump(frontmatter, { lineWidth: -1, quotingType: '"', forceQuotes: false });

    // Body: system prompt for the subagent
    let body = profile.description + "\n";
    if (profile.servers.length > 0) {
      const prompt = profile.systemPrompt ??
        "You have MCP tools (mcp__*) available. Prefer using MCP tools over built-in alternatives like Fetch, WebFetch, or WebSearch.";
      body += "\n" + prompt + "\n";
    }

    const content = `---\n${yamlStr}---\n\n${body}\n${GENERATED_MARKER}\n`;
    atomicWrite(filePath, content);
    generated.push(filePath);
  }

  return generated;
}

/**
 * Generate .claude/rules/sub-mcp.md so the main agent knows which
 * subagent profiles exist and when to use them.
 */
export function generateRulesFile(config: SubMcpConfig, projectDir: string): string {
  const rulesDir = join(projectDir, ".claude", "rules");
  mkdirSync(rulesDir, { recursive: true });

  const filePath = join(rulesDir, "sub-mcp.md");

  let content = "# Sub-MCP Profiles\n\n";
  content += "The following subagent profiles are available in `.claude/agents/`.\n";
  content += "Use them with the Agent tool by setting `subagent_type` to the profile name.\n\n";

  for (const [name, profile] of Object.entries(config.profiles)) {
    const servers = profile.servers.length > 0 ? profile.servers.join(", ") : "none";
    const model = profile.model ? `, model: ${profile.model}` : "";
    content += `- **${name}** — ${profile.description} (servers: ${servers}${model})\n`;
  }

  if (config.defaults?.profile) {
    content += `\nDefault profile: **${config.defaults.profile}**\n`;
  }

  content += `\n${GENERATED_MARKER}\n`;

  atomicWrite(filePath, content);
  return filePath;
}

/** Remove generated agent files and rules file if they have the generated marker. */
export function cleanGeneratedFiles(projectDir: string): string[] {
  const removed: string[] = [];
  const agentsDir = join(projectDir, ".claude", "agents");
  const rulesFile = join(projectDir, ".claude", "rules", "sub-mcp.md");

  // Clean agent files
  if (existsSync(agentsDir)) {
    for (const file of readdirSync(agentsDir)) {
      if (!file.endsWith(".md")) continue;
      const filePath = join(agentsDir, file);
      try {
        const content = readFileSync(filePath, "utf-8");
        if (content.includes(GENERATED_MARKER)) {
          rmSync(filePath);
          removed.push(filePath);
        }
      } catch { /* skip files we can't read */ }
    }
  }

  // Clean rules file
  if (existsSync(rulesFile)) {
    try {
      const content = readFileSync(rulesFile, "utf-8");
      if (content.includes(GENERATED_MARKER)) {
        rmSync(rulesFile);
        removed.push(rulesFile);
      }
    } catch { /* skip */ }
  }

  return removed;
}

const program = new Command();

program
  .name("sub-mcp")
  .description("sub-mcp — zero-overhead MCP proxy for AI coding agents")
  .version("0.1.0");

program
  .command("query")
  .description("Send a query through a named MCP profile")
  .requiredOption("-p, --profile <name>", "Profile to use")
  .option("--raw", "Output raw text only")
  .option("--model <model>", "Override the model")
  .option("--config <path>", "Path to config file")
  .argument("<prompt>", "The prompt to send")
  .action(async (prompt: string, opts: Record<string, string | boolean | undefined>) => {
    try {
      const config = loadConfig(opts.config as string | undefined);
      const result = await query(config, opts.profile as string, prompt, {
        model: opts.model as string | undefined,
      });

      if (opts.raw) {
        process.stdout.write(result.text + "\n");
      } else {
        console.log(JSON.stringify(result, null, 2));
      }
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  });

program
  .command("profiles")
  .description("List available profiles")
  .option("--config <path>", "Path to config file")
  .action((opts: Record<string, string | undefined>) => {
    try {
      const config = loadConfig(opts.config as string | undefined);

      for (const [name, profile] of Object.entries(config.profiles)) {
        const servers =
          profile.servers.length > 0 ? profile.servers.join(", ") : "(none)";
        const model = profile.model ?? "(inherited)";
        console.log(`  ${name}`);
        console.log(`    ${profile.description}`);
        console.log(`    servers: ${servers}  model: ${model}`);
        console.log();
      }
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  });

program
  .command("install")
  .description("Install the transparent claude wrapper for MCP injection")
  .option("--config <path>", "Path to profiles.yml")
  .option("--no-agents", "Skip generating .claude/agents/ files")
  .action((opts: Record<string, string | boolean | undefined>) => {
    try {
      const config = loadConfig(opts.config as string | undefined);

      // Find real claude — skip ~/.sub-mcp/bin to avoid finding our own wrapper
      const pathDirs = (process.env.PATH ?? "")
        .split(":")
        .filter((d) => d !== BIN_DIR);
      const envWithoutSubMcp = { ...process.env, PATH: pathDirs.join(":") };
      const realClaude = execSync("which claude", {
        encoding: "utf-8",
        env: envWithoutSubMcp,
      }).trim();

      if (!realClaude) {
        console.error("Error: claude CLI not found in PATH");
        process.exit(1);
      }

      // Create dirs
      mkdirSync(BIN_DIR, { recursive: true });

      // Save real claude path (atomic)
      atomicWrite(join(SUB_MCP_DIR, "real-claude-path"), realClaude);

      // Pre-compute MCP config cache — includes profiles and defaults so the
      // wrapper can filter by SUB_MCP_PROFILE. Env vars kept as ${VAR} placeholders,
      // resolved at runtime. No secrets on disk.
      atomicWrite(join(SUB_MCP_DIR, "mcp-config.json"), JSON.stringify(buildCache(config)), 0o600);

      // Copy profiles.yml to ~/.sub-mcp/ so `sub-mcp refresh` works from any directory
      const configSource = findConfigSourcePath(opts.config as string | undefined);
      if (configSource) {
        copyFileSync(configSource, join(SUB_MCP_DIR, "profiles.yml"));
      }

      // Install wrapper + argv helper to ~/.sub-mcp/bin/
      const wrapperDst = join(BIN_DIR, "claude");
      copyFileSync(join(__dirname, "wrapper.js"), wrapperDst);
      chmodSync(wrapperDst, 0o755);
      copyFileSync(join(__dirname, "argv.js"), join(BIN_DIR, "argv.js"));

      console.log(`Installed wrapper to ${wrapperDst}`);
      console.log(`Real claude: ${realClaude}`);
      console.log(`MCP servers: ${Object.keys(config.mcpServers).join(", ")}`);

      // Generate .claude/agents/ and .claude/rules/ files for interactive sessions
      if (opts.agents !== false) {
        const projectDir = process.cwd();
        const agentFiles = generateAgentFiles(config, projectDir);
        const rulesFile = generateRulesFile(config, projectDir);
        console.log(`\nGenerated ${agentFiles.length} agent file(s) in .claude/agents/`);
        console.log(`Generated rules file: ${rulesFile}`);
      }

      // Check PATH
      if (!process.env.PATH?.split(":").includes(BIN_DIR)) {
        console.log(
          `\nAdd to your shell profile:\n  export PATH="$HOME/.sub-mcp/bin:$PATH"\n`
        );
      } else {
        console.log("\nReady. Subagents will now have MCP access.");
      }
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  });

program
  .command("uninstall")
  .description("Remove the claude wrapper and generated agent files")
  .action(() => {
    const errors: string[] = [];
    const files = [
      join(BIN_DIR, "claude"),
      join(BIN_DIR, "argv.js"),
      join(SUB_MCP_DIR, "real-claude-path"),
      join(SUB_MCP_DIR, "mcp-config.json"),
    ];
    for (const f of files) {
      try {
        if (existsSync(f)) rmSync(f);
      } catch (err) {
        errors.push(`Failed to remove ${f}: ${(err as Error).message}`);
      }
    }

    // Clean generated agent/rules files in CWD
    const removed = cleanGeneratedFiles(process.cwd());
    if (removed.length > 0) {
      console.log(`Removed ${removed.length} generated file(s)`);
    }

    if (errors.length > 0) {
      console.error(errors.join("\n"));
    }
    console.log("Uninstalled. Subagents will use claude directly.");
  });

program
  .command("refresh")
  .description("Re-read profiles.yml and update MCP config + agent files")
  .option("--config <path>", "Path to profiles.yml")
  .action((opts: Record<string, string | undefined>) => {
    try {
      const config = loadConfig(opts.config);
      atomicWrite(join(SUB_MCP_DIR, "mcp-config.json"), JSON.stringify(buildCache(config)), 0o600);
      console.log(
        `Updated MCP config: ${Object.keys(config.mcpServers).join(", ")}`
      );

      // Regenerate agent files in CWD
      const projectDir = process.cwd();
      cleanGeneratedFiles(projectDir);
      const agentFiles = generateAgentFiles(config, projectDir);
      generateRulesFile(config, projectDir);
      console.log(`Regenerated ${agentFiles.length} agent file(s)`);
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  });

program
  .command("agents")
  .description("Generate .claude/agents/ and .claude/rules/ files from profiles")
  .option("--config <path>", "Path to profiles.yml")
  .option("--clean", "Remove generated files instead of generating")
  .action((opts: Record<string, string | boolean | undefined>) => {
    try {
      if (opts.clean) {
        const removed = cleanGeneratedFiles(process.cwd());
        if (removed.length > 0) {
          console.log(`Removed ${removed.length} generated file(s):`);
          for (const f of removed) console.log(`  ${f}`);
        } else {
          console.log("No generated files found.");
        }
        return;
      }

      const config = loadConfig(opts.config as string | undefined);
      const projectDir = process.cwd();

      // Clean old generated files first
      cleanGeneratedFiles(projectDir);

      const agentFiles = generateAgentFiles(config, projectDir);
      const rulesFile = generateRulesFile(config, projectDir);

      console.log(`Generated ${agentFiles.length} agent file(s):`);
      for (const f of agentFiles) console.log(`  ${f}`);
      console.log(`Generated rules: ${rulesFile}`);
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  });

program
  .command("debug")
  .description("Show the resolved MCP config that would be injected into subagents")
  .option("--config <path>", "Path to profiles.yml")
  .action((opts: Record<string, string | undefined>) => {
    try {
      const config = loadConfig(opts.config);

      const cacheFile = join(SUB_MCP_DIR, "mcp-config.json");
      const realClaudeFile = join(SUB_MCP_DIR, "real-claude-path");
      const wrapperPath = join(BIN_DIR, "claude");

      console.log("Wrapper status:");
      console.log(`  wrapper:      ${existsSync(wrapperPath) ? wrapperPath : "(not installed)"}`);
      console.log(`  real claude:  ${existsSync(realClaudeFile) ? readFileSync(realClaudeFile, "utf-8").trim() : "(not set)"}`);
      console.log(`  mcp cache:    ${existsSync(cacheFile) ? cacheFile : "(not generated)"}`);
      console.log();

      console.log("Configured MCP servers:");
      for (const [name, server] of Object.entries(config.mcpServers)) {
        const envVars = server.env ? ` env: ${Object.keys(server.env).join(", ")}` : "";
        console.log(`  ${name}: ${server.command} ${server.args.join(" ")}${envVars}`);
      }
      console.log();

      console.log("Profiles:");
      for (const [name, profile] of Object.entries(config.profiles)) {
        const servers = profile.servers.length > 0 ? profile.servers.join(", ") : "(none)";
        const model = profile.model ?? "(inherited)";
        const isolated = profile.isolateMcp ? " (isolated)" : " (inherits parent MCPs)";
        console.log(`  ${name}: ${profile.description}`);
        console.log(`    servers: ${servers}${profile.servers.length > 0 ? isolated : ""}  model: ${model}`);
      }
      console.log();

      if (existsSync(cacheFile)) {
        console.log("Resolved MCP config (injected on claude -p calls):");
        const raw = readFileSync(cacheFile, "utf-8");
        console.log(JSON.stringify(JSON.parse(raw), null, 2));
      }
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  });

// Only run when executed directly, not when imported for testing.
// Compare real paths to handle npm link symlinks.
const _self = fileURLToPath(import.meta.url);
const _argv1 = process.argv[1];
if (_argv1 && (realpathSync(_argv1) === _self || realpathSync(_argv1) === realpathSync(_self))) {
  program.parse();
}
